version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  searchservice:
    image: alexcogojocaru/ep:searchservice
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    deploy:
      replicas: 4

  steamcrawlerserver:
    image: alexcogojocaru/ep:steamcrawlerserver
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 2

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - steamcrawlerserver
    ports:
      - "4000:4000"